### ISSUE TITLE
DB schema missing

### ISSUE THREAD

**Issue by tobru** [krethjr/mysommelier#1]
I wanted to give this app a try but it seems to lack a SQL file to create the database structure. Are you able to provide one?

**Comment by krethjr** [comment]
Tobias,

I have the schema in MySQL Workbench.  I'll add that source file and the full create-db sql script in case you don't use workbench.  I should have it posted by this evening. I've also made some uncommitted changes that I'll make sure get pushed up.

**Comment by tobru** [comment]
I'm not using workbench, so it would be great to have a SQL file to initialize the database.  Thanks a lot

**Comment by krethjr** [comment]
I just committed "wine_cellar_mysql_create.sql" to the main.  It's the full MySQL create script.

**Comment by tobru** [comment]
Thanks, will test it soon!
