### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by nncrypted** [krethjr/mysommelier#2]
Is there any installation instructions. I thought I had it installed but I only get errors. BTW running on Linux tried Ubuntu 14.04 server and now on Debian Jessie

**Comment by krethjr** [comment]
@nncrypted, I develop on win7 using WAMPServer 2.5 but I run my personal prod server on a hosted Linux server (Centos 6 I believe).  I'll create an installation doc and commit it to the project this weekend.  I use composer to keep all the extensions up-to-date on my dev box, but when I move it to prod, I then Zip - FTP - Unzip the entire dev folder on the prod server, then remove unneeded files and adjust permissions.

**Comment by nncrypted** [comment]
Thank you much appreciated.  I'm the maintainer and driver for my wifes collection. We live in Niagara region so wine tasting weekends is a regular occurrence.

**Comment by nncrypted** [comment]
Everytime I think I've got it figured out I get this:  PHP Notice – yii\base\ErrorException
Trying to get property of non-object  in /var/www/mysommelier/controllers/SiteController.php at line 59

**Comment by nncrypted** [comment]
Any progress with this?

**Comment by nncrypted** [comment]
Bump. Can point me in the right direction. Please
